// todo/Source/examination/exam-reports/student-backlog-data/student-backlog-data.component.ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { SnotifyService } from 'ng-snotify';
import { NgxSpinnerService } from 'ngx-spinner';
import { ActivatedRoute, Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { RouterModule } from '@angular/router';
import { ChangeDetectorRef } from '@angular/core';


import { CONSTANTS } from 'app/main/common/constants';
import { CrudService } from 'app/main/services/crud.service';
import { FeeCategory } from 'app/main/models/feeCategory';
import { College } from 'app/main/models/college';
import { AcademicYear } from 'app/main/models/academicYear';
import { MatDialog } from '@angular/material/dialog';
import { GenericFunctions } from 'app/main/common/generic-functions';
import { MatRadioChange } from '@angular/material/radio';
import { EditStructureComponent } from 'app/main/apps/accounts-and-fees/fee-masters/fee-structure/edit-structure/edit-structure.component';
import { ViewStructureComponent } from 'app/main/apps/accounts-and-fees/fee-masters/fee-structure/view-structure/view-structure.component';

@Component({
  selector: 'app-student-backlog-data',
  templateUrl: './student-backlog-data.component.html',
  styleUrls: ['./student-backlog-data.component.scss']
})
export class StudentBacklogDataComponent implements OnInit {
  displayedColumns: string[] = [
    'siNo',
    'hallticket_number',
    'course_year_code',
    'failed_subjects',
    'semester_failed_count',
    'total_failed_count'
  ];

  dataSource: MatTableDataSource<FeeCategory>;

  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild('excelTable', { static: false }) excelTable!: ElementRef;
  trafoItem = "Student Backlog Data";

  private collegeWiseDetails = CONSTANTS.collegeWiseDetailsUrl;
  private collegeCrudUrl = CONSTANTS.collegeCrudUrl;
  private batchCrudUrl = CONSTANTS.batchCrudUrl;
  private getDetailsByUniversityIdUrl = CONSTANTS.getDetailsByUniversityIdUrl;
  private FeeStructureUrl = CONSTANTS.FeeStructureUrl;
  private academicYearCrudUrl = CONSTANTS.academicYearCrudUrl;
  private getDetailsByCollegeIdUrl = CONSTANTS.getDetailsByCollegeIdUrl;
  private isActive = CONSTANTS.isActive;

  staffForm: FormGroup;
  filtersDetailsList = [];
  filtersdata = [];
  academicyears = [];
  academicYearData = [];
  feeStructures: any[] = [];
  colleges: College[] = [];
  examsList = [];
  defaultAcademicYear: number;
  academicYears: AcademicYear[] = [];
  totalCount = 0;
  pageIndex = 0;
  collegeLogo = [];
  isPrintMode: boolean = false;
  pageSize = 0;
  panelOpenState = true;
  step = 0;
  collegeName;
  examSubjectStats = [];
  params: any = {};
  exam: any;
  Logo: any;
  check = 1;
  batches = [];
  courseCodes = [];
  subjects = [];
  examRegisteredStudents = [];
  mainList = [];
  courseData = [];
  courses = [];
  batchesFilter = [];
  batchesData = [];
  flag = false;
  isAcademicFee: any;

  constructor(private route: ActivatedRoute, private formBuilder: FormBuilder, private dialog: MatDialog,
    private snotifyService: SnotifyService, private genericFunctions: GenericFunctions,
    private crudService: CrudService, private spinner: NgxSpinnerService, public router: Router, private cdr: ChangeDetectorRef) {
    this.defaultAcademicYear = +localStorage.getItem('academicYearId');
    // this.getFeeStructures();

    this.route.queryParams
      .subscribe(params => {
        if (!this.isEmptyObject(params)) {
          this.params = params;
          this.isAcademicFee = this.params.isAcademicFee === 'true';
        }
      });


  }

  // tslint:disable-next-line:typedef
  ngOnInit() {
    this.staffForm = this.formBuilder.group({
      collegeId: ['', Validators.required],
      courseId: [''],
      batchId: ['', Validators.required],
      academicYearId: [''],
    });

    // this.getData();
    this.getfilterDetails();
    this.dataSource = new MatTableDataSource(this.feeStructures);
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }


  // tslint:disable-next-line:typedef
  isEmptyObject(obj) {
    return (obj && (Object.keys(obj).length === 0));
  }

  getfilterDetails() {
    this.spinner.show()
    let request = [
      { paramName: 'in_flag', paramValue: 'clg_filters' },
      { paramName: 'in_org_id', paramValue: +localStorage.getItem('organizationId') },
      { paramName: 'in_college_id', paramValue: 0 },
      { paramName: 'in_course_id', paramValue: 0 },
      { paramName: 'in_course_group_id', paramValue: 0 },
      { paramName: 'in_course_year_id', paramValue: 0 },
      { paramName: 'in_group_section_id', paramValue: 0 },
      { paramName: 'in_academic_year_id', paramValue: 0 },
      { paramName: 'in_dept_id', paramValue: 0 },
      { paramName: 'in_isadmin', paramValue: 0 },
      { paramName: 'in_loginuser_empid', paramValue: +localStorage.getItem('employeeId') },
      { paramName: 'in_loginuser_roleid', paramValue: 0 },
      { paramName: 'in_subject', paramValue: '' },
      { paramName: 'in_employee', paramValue: '' },
      { paramName: 'in_gm_codes', paramValue: '' },
    ];
    this.crudService.getDetailsByRequest(this.collegeWiseDetails, '', request, '&')
      .subscribe(result => {
        if (result.statusCode === 200) {
          this.spinner.hide()
          if (result.data && result.data !== '' && result.data.result.length > 0) {
            this.filtersDetailsList = result.data.result;
            for (let i = 0; i < this.filtersDetailsList.length; i++) {
              if (this.filtersDetailsList[i].length > 0 && this.filtersDetailsList[i][0].flag === 'clg_filters') {
                this.filtersdata = this.filtersDetailsList[i];
              } else if (this.filtersDetailsList[i].length > 0 && this.filtersDetailsList[i][0].clg_filters_ay === 'clg_filters_ay') {
                this.academicYearData = this.filtersDetailsList[i];
              } else if (this.filtersDetailsList[i].length > 0 && this.filtersDetailsList[i][0].clg_filters_batches === 'clg_filters_batches') {
                this.batchesFilter = this.filtersDetailsList[i];
              }
            }
            /*----------- DISTINCT COLLEGE-----------*/
            const collegeList = this.filtersdata.map(({ fk_college_id }) => fk_college_id);
            this.colleges = this.filtersdata.filter(({ fk_college_id }, index) =>
              !collegeList.includes(fk_college_id, index + 1));
            if (!this.isEmptyObject(this.params) && this.colleges.length > 0) {
              this.staffForm.get('collegeId').setValue(+this.params.cId);
              this.selectedCollege(this.staffForm.value.collegeId);
            } else
              if (this.colleges && this.colleges.length > 0) {
                this.colleges = this.colleges.sort((a, b) => a.clg_sort_order - b.clg_sort_order);
                this.staffForm.get('collegeId').setValue(this.colleges[0].fk_college_id);
                this.selectedCollege(this.staffForm.value.collegeId);
              }
          } else {
            this.snotifyService.success(result.message, 'Success!');
          }
        } else {
          this.spinner.hide()
          this.snotifyService.error(result.message, 'Error!');
        }
      }, error => {
        if (error.error.statusCode === 401) {
          this.snotifyService.error(error.error.message, 'Error!');
          this.genericFunctions.logOut(this.router.url);
        } else {
          this.snotifyService.error(CONSTANTS.message.CON_ERROR, 'Error!');
        }
      });
  }
  getDetails() {
    this.examSubjectStats = [];
    this.examRegisteredStudents = [];
    this.mainList = [];
    this.courseCodes = [];

    if (this.staffForm.valid) {
      this.spinner.show();

      const request = [
        { paramName: 'in_flag', paramValue: 'STUDENT_FAILURE_SUMMARY' },
        { paramName: 'in_college_id', paramValue: this.staffForm.value.collegeId },
        { paramName: 'in_course_id', paramValue: this.staffForm.value.courseId },
        { paramName: 'in_course_group_id', paramValue: 0 },
        { paramName: 'in_course_year_id', paramValue: 0 },
        { paramName: 'in_exam_id', paramValue: 0 },
        { paramName: 'in_batch_id', paramValue: this.staffForm.value.batchId }
      ];

      this.crudService.getDetailsByRequest('getAllRecords/s_generate_exam_reports', '', request, '&')
        .subscribe({
          next: (result) => {
            this.spinner.hide();

            if (result.statusCode === 200) {
              const resultData = result.data?.result;
              if (Array.isArray(resultData) && Array.isArray(resultData[0])) {
                const flatRows = resultData[0] as any[];        // 2760 flat records

                // 1) Build dynamic semester columns from ALL rows
                const uniqueCourseYears = [...new Set(flatRows.map(x => x.course_year_code))];
                this.courseCodes = uniqueCourseYears.map(code => ({ course_year_code: code }));

                // 2) Group rows by hallticket_number => each table row is an ARRAY of that student's semester objects
                const groups: Record<string, any[]> = {};
                for (const r of flatRows) {
                  const key = r.hallticket_number;
                  if (!groups[key]) groups[key] = [];
                  groups[key].push(r);
                }
                this.mainList = Object.values(groups);          // Array< Array<semesterObj> >
                this.examRegisteredStudents = flatRows;         // keep for any other uses
                this.examSubjectStats = flatRows;               // if you gate rendering on this

                this.cdr.detectChanges();
              } else {
                this.mainList = [];
                this.examRegisteredStudents = [];
                this.courseCodes = [];
              }



              // ✅ Build dynamic columns (unique course_year_code)
              if (this.examRegisteredStudents?.length > 0) {
                const courseYearList = this.examRegisteredStudents.map(x => x.course_year_code);
                const uniqueCourseYears = [...new Set(courseYearList)];

                this.courseCodes = uniqueCourseYears.map(code => ({
                  course_year_code: code
                }));
              }

              if (this.mainList.length === 0) {
                this.snotifyService.info('No data found for selected filters.', 'Info');
              }
            } else {
              this.snotifyService.error(result.message, 'Error!');
            }
          },
          error: () => {
            this.spinner.hide();
            this.snotifyService.error(CONSTANTS.message.CON_ERROR, 'Error!');
          }
        });

    } else {
      this.snotifyService.warning('Please select all required fields.', 'Warning');
    }
  }

  findMarks(list: any[], courseYearCode: string, field: string) {
    if (Array.isArray(list)) {
      const item = list.find(x => x.course_year_code === courseYearCode);
      return item ? (item[field] ?? '-') : '-';
    }
    return '-';
  }






  getColleges(): void {
    this.collegeLogo = [];
    this.Logo = [];
    /*----------- COLLEGES -----------*/
    this.crudService.listDetailsById(this.collegeCrudUrl, 'true', 'isActive')
      .subscribe(result => {
        if (result.statusCode === 200) {
          if (result.data.resultList && result.data.resultList !== '') {
            this.collegeLogo = result.data.resultList;
            this.Logo = this.collegeLogo.filter(x => (x.collegeId == this.staffForm.value.collegeId))[0].logo
            this.collegeName = this.collegeLogo.filter(x => (x.collegeId == this.staffForm.value.collegeId))[0].collegeName
          } else {
            this.snotifyService.success(result.message, 'Success!');
          }
        } else {
          this.snotifyService.error(result.message, 'Error!');
        }
      }, error => {
        if (error.error.statusCode === 401) {
          this.snotifyService.error(error.error.message, 'Error!');
          this.genericFunctions.logOut(this.router.url);
        } else {
          this.snotifyService.error(CONSTANTS.message.CON_ERROR, 'Error!');
        }
      });
  }

  selectedCourse(courseId) {
    this.staffForm.get('batchId').setValue('')
    this.batchesData = [];
    this.batches = [];
    this.flag = false;
    this.mainList = [];
    this.feeStructures = [];
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
    this.batchesData = this.batchesFilter.filter(x => (x.fk_course_id === this.staffForm.value.courseId));
    if (this.batchesData && this.batchesData.length > 0) {
      const batcheList = this.batchesData.map(({ fk_batch_id }) => fk_batch_id);
      this.batches = this.batchesData.filter(({ fk_batch_id }, index) =>
        !batcheList.includes(fk_batch_id, index + 1));
    }
    if (!this.isEmptyObject(this.params) && this.batches.length > 0) {
      this.mainList = [];
      this.batches = this.batches.sort((a, b) => parseInt(b.batch_name) - parseInt(a.batch_name))
      this.staffForm.get('batchId').setValue(+this.params.batchId);
      this.selectedBatch(this.staffForm.value.batchId)
    } else if (this.batches && this.batches.length > 0) {
      this.batches = this.batches.sort((a, b) => parseInt(b.batch_name) - parseInt(a.batch_name))
      this.staffForm.get('batchId').setValue(this.batches[0].fk_batch_id);
      this.selectedBatch(this.staffForm.value.batchId);
    }
  }
  selectedBatch(batchId) {
    this.flag = true;
    this.feeStructures = [];
  this.examSubjectStats = [];
    this.examRegisteredStudents = [];
    this.mainList = [];
    this.courseCodes = [];

    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;

  }
  selectedCollege(collegeId): void {
    this.batches = [];
    this.Logo = [];
    this.flag = false;
    this.feeStructures = [];
    this.examSubjectStats = [];
    this.examRegisteredStudents = [];
    this.mainList = [];
    this.courseCodes = [];
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
    /*----------- ACADEMIC YEARS -----------*/
    // this.batchesData = this.batchesFilter.filter(x=>(x.fk_course_id === this.staffForm.value.courseId));

    this.courseData = this.filtersdata.filter(x => (x.fk_college_id == this.staffForm.value.collegeId));

    if (this.courseData.length > 0) {
      const Course_Id = this.courseData.map(({ fk_course_id }) => fk_course_id);
      this.courses = this.courseData.filter(({ fk_course_id }, index) =>
        !Course_Id.includes(fk_course_id, index + 1));
    }
    if (!this.isEmptyObject(this.params) && this.courses.length > 0) {
      this.staffForm.get('courseId').setValue(+this.params.courseId);
      this.selectedCourse(this.staffForm.value.courseId);
    } else if (this.courses.length > 0) {
      this.staffForm.get('courseId').setValue(this.courses[0].fk_course_id);
      this.selectedCourse(this.staffForm.value.courseId);
    }
    this.crudService.listDetailsById(this.collegeCrudUrl, 'true', 'isActive')
      .subscribe(result => {
        if (result.statusCode === 200) {
          if (result.data.resultList && result.data.resultList !== '') {
            this.collegeLogo = result.data.resultList;
            this.Logo = this.collegeLogo.filter(x => (x.collegeId == this.staffForm.value.collegeId))[0].logo
            this.collegeName = this.collegeLogo.filter(x => (x.collegeId == this.staffForm.value.collegeId))[0].collegeName
          } else {
            this.snotifyService.success(result.message, 'Success!');
          }
        } else {
          this.snotifyService.error(result.message, 'Error!');
        }
      }, error => {
        if (error.error.statusCode === 401) {
          this.snotifyService.error(error.error.message, 'Error!');
          this.genericFunctions.logOut(this.router.url);
        } else {
          this.snotifyService.error(CONSTANTS.message.CON_ERROR, 'Error!');
        }
      });


  }


  // tslint:disable-next-line:typedef
  applyFilter(filterValue: string) {
    this.dataSource.filter = filterValue.trim().toLowerCase();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }


  //print functions(excel,print)

  exportAsExcel(): void {
    if (!this.excelTable || !this.excelTable.nativeElement) {
      console.error('Excel table not found or not rendered yet.');
      return;
    }

    // Add heading manually before table
    const heading = `
      <tr>
        <th colspan="6" style="text-align:center; font-size:21px; font-weight:bold; background:#f2f2f2;">
          Student Backlog Data
        </th>
      </tr>
    `;

    const uri = 'data:application/vnd.ms-excel;base64,';
    const template = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office"
            xmlns:x="urn:schemas-microsoft-com:office:excel"
            xmlns="http://www.w3.org/TR/REC-html40">
        <head>
          <!--[if gte mso 9]>
          <xml>
            <x:ExcelWorkbook>
              <x:ExcelWorksheets>
                <x:ExcelWorksheet>
                  <x:Name>{worksheet}</x:Name>
                  <x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions>
                </x:ExcelWorksheet>
              </x:ExcelWorksheets>
            </x:ExcelWorkbook>
          </xml>
          <![endif]-->
        </head>
        <body><table>{table}</table></body>
      </html>`;

    const base64 = (s: string) => window.btoa(unescape(encodeURIComponent(s)));
    const format = (s: string, c: any) => s.replace(/{(\w+)}/g, (m, p) => c[p]);

    // inject heading before table rows
    const tableHTML = heading + this.excelTable.nativeElement.innerHTML;
    const ctx = { worksheet: 'StudentBacklog', table: tableHTML };

    const link = document.createElement('a');
    link.download = `${this.trafoItem}.xls`;
    link.href = uri + base64(format(template, ctx));
    link.click();
  }

  Print() {
    this.isPrintMode = true;
    setTimeout(() => {
      window.print();
      this.isPrintMode = false;
    }, 500);
  }


}

<div id="dashboard" class="page-layout simple" id="printNone" *ngIf="!isPrintMode">
  <div class="center" fusePerfectScrollbar>

    <!-- HEADER -->
    <div class="header pd-dash" fxLayout="column" fxLayoutAlign="space-between">

      <div fxLayout="column" class="link-header" fxLayoutAlign="center center" fxLayout.gt-xs="column"
        fxLayoutAlign.gt-xs="center start">
        <div class="black-fg" fxLayout="row" fxLayoutAlign="start center">
          <mat-icon class="secondary-text s-18 cursr" [routerLink]="'/dashboard'">home</mat-icon>
          <mat-icon class="secondary-text s-16">chevron_right</mat-icon>
          <span>Examination Management</span>
          <mat-icon class="secondary-text s-16">chevron_right</mat-icon>
          <span>Exam Reports</span>
          <mat-icon class="secondary-text s-16">chevron_right</mat-icon>
          <span>Student Backlog Data</span>
        </div>
      </div>

    </div>
    <!-- / HEADER -->

    <!-- CONTENT -->
    <div class="content">

      <mat-accordion style="width: 100%;padding: 22px 24px 0px 24px;">
        <mat-expansion-panel [expanded]="step === 0" hideToggle style="margin: 0px 25px;">
          <mat-expansion-panel-header>
            <mat-panel-title>
              <div fxLayout="column" fxLayoutAlign="center center" fxLayout.gt-xs="column"
                fxLayoutAlign.gt-xs="center start">
                <div class="black-fg" fxLayout="row" fxLayoutAlign="start center">
                  <i class="fa fa-user-plus icon-align" aria-hidden="true"></i>
                  <strong class="table-heads">Student Backlog Data</strong>
                </div>
              </div>
            </mat-panel-title>
            <label class="filter-align">Filter</label>
            <mat-icon>filter_list</mat-icon>
          </mat-expansion-panel-header>
          <form name="staffForm" [formGroup]="staffForm" novalidate>
            <div fxLayout="row" fxLayoutGap="10px">
              <!-- College dropdown -->
              <mat-form-field fxLayout="column" class="p-8" fxFlex="100" fxFlex.gt-xs="40" fxFlex.gt-md="40">
                <mat-select placeholder="College" name="collegeId" formControlName="collegeId"
                  (selectionChange)="selectedCollege(staffForm.value.collegeId)" required>
                  <mat-option *ngFor="let college of colleges" [value]="college.fk_college_id">
                    {{ college.college_code }}
                  </mat-option>
                </mat-select>
              </mat-form-field>
              <mat-form-field fxLayout="column" class="p-8" fxFlex="100" fxFlex.gt-xs="33" fxFlex.gt-md="33"
                *ngIf="check === 1">
                <mat-select placeholder="Course" name="courseId" formControlName="courseId"
                  (selectionChange)="selectedCourse(staffForm.value.courseId)" required>
                  <mat-option *ngFor="let course of courses" [value]="course.fk_course_id"
                    matTooltip="{{course.course_name}}({{course.course_code}})">{{course.course_code}}</mat-option>
                </mat-select>
              </mat-form-field>

              <!-- Batch dropdown -->
              <mat-form-field fxLayout="column" class="p-8" fxFlex="100" fxFlex.gt-xs="40" fxFlex.gt-md="40"
                *ngIf="check === 1">
                <mat-select placeholder="Batch" name="batchId" formControlName="batchId"
                  (selectionChange)="selectedBatch(staffForm.value.batchId)" required>
                  <mat-option *ngFor="let batches of batches" [value]="batches.fk_batch_id">
                    {{ batches.batch_name }}
                  </mat-option>
                </mat-select>
              </mat-form-field>

              <!-- Buttons -->
              <div fxLayout="row" fxLayoutAlign="start center" fxFlex="100" fxFlex.gt-xs="20" fxFlex.gt-md="20">
                <div class="savebtn-align" fxFlex="70">
                  <button mat-raised-button class="add-btn" color="accent" (click)="getDetails()">
                    Get Report
                  </button>
                </div>

              </div>
            </div>
          </form>

        </mat-expansion-panel>
        <mat-expansion-panel (opened)="panelOpenState = true" (closed)="panelOpenState = false">
        </mat-expansion-panel>
      </mat-accordion>
      <div class="header pd-pag2" fxLayout="column" fxLayoutAlign="space-between" *ngIf="this.mainList.length>0">

        <div fxLayout="column" class="page-table-head" fxLayoutAlign="center center" fxLayout.gt-xs="column"
          fxLayoutAlign.gt-xs="center start">
          <div class="black-fg" fxLayout="row" fxLayoutAlign="start center">
            <!-- <mat-icon class="secondary-text fs icon-align">assessment</mat-icon> -->
            <i class="fa fa-th-large icon-align" aria-hidden="true"></i>
            <!-- <h1 class="secondary-text table-head fs-20">Blocks</h1> -->
            <strong class="table-heads">Student Backlog Data</strong>
          </div>
        </div>


      </div>

      <mat-card class="pd-card table-align" *ngIf="mainList.length > 0">
        <mat-card-content>
          <div fxLayout="row" fxLayout.xs="column" class="search-align" fxLayoutAlign="space-between" fxLayoutGap="5">
            <div fxFlex.gt-xs="28" fxFlex.gt-md="28" fxLayout="row" fxLayoutAlign="start center" class="align-items">
              <button mat-raised-button class="add-btn" color="accent" (click)="exportAsExcel()">
                <i class="fa fa-file-excel-o icon" aria-hidden="true"></i>Export Excel</button>
              <button mat-raised-button class="add-btn ptnbtn" color="accent" (click)="Print()">
                <i class="fa fa-print icon" aria-hidden="true"></i>Print Report</button>

            </div>

          </div>
        </mat-card-content>
        <div class="mat-elevation-z8" *ngIf="mainList.length > 0">
          <div class="example-container" #excelTable>
            <table id="table" class="mar">
              <thead>
                <tr>
                  <th class="table-th" rowspan="2">Sno</th>
                  <th class="table-th" rowspan="2">Hall ticket number</th>
                  <th class="table-th" rowspan="2">Group code</th>

                  <!-- ✅ Dynamic Semester Headers -->
                  <ng-container *ngFor="let cour of courseCodes">
                    <th class="table-th" colspan="2">
                      {{ cour.course_year_code }}
                    </th>
                  </ng-container>

                  <th class="table-th" rowspan="2">Total Fail</th>
                </tr>

                <tr>
                  <!-- ✅ Second row below each Semester -->
                  <ng-container *ngFor="let cour of courseCodes">
                    <th class="table-th">Count</th>
                    <th class="table-th">Subjects</th>
                  </ng-container>
                </tr>
              </thead>

              <tbody>
                <tr *ngFor="let list of mainList; let i = index">
                  <td class="table-td">{{ i + 1 }}</td>
                  <td class="table-td">{{ list[0]?.hallticket_number }}</td>
                  <td class="table-td">{{ list[0]?.group_code }}</td>

                  <ng-container *ngFor="let cour of courseCodes">
                    <td class="table-td">
                      {{ findMarks(list, cour.course_year_code, 'semester_failed_count') }}
                    </td>
                    <td class="table-td">
                      {{ findMarks(list, cour.course_year_code, 'failed_subjects') }}
                    </td>
                  </ng-container>

                  <td class="table-td">{{ list[0]?.total_failed_count }}</td>
                </tr>
              </tbody>


            </table>

          </div>

          <mat-paginator [pageSize]="10" [pageSizeOptions]="[10, 25, 50]" showFirstLastButtons>
          </mat-paginator>
        </div>

      </mat-card>

    </div>
  </div>
</div>
<div id="printSection" style="width: 98% !important;">

  <!-- HEADER ROW FIXED -->
  <div class="print-header-container">

    <!-- LOGO Left -->
    <div class="logo-container">
      <img class="portraitLogo" [src]="Logo ? Logo : 'assets/images/avatars/default_logo.png'">
    </div>

    <!-- TEXT CENTER -->
    <div class="text-section">
      <p class="collegeName">{{ collegeName }}</p>
      <p class="title">Student Backlog Data</p>
    </div>

  </div>

  <!-- TABLE -->
  <table class="subject-table-refined">
    <thead>
      <tr>
        <th rowspan="2">S.No</th>
        <th rowspan="2">Hall Ticket No</th>
        <th rowspan="2">Group Code</th>

        <!-- ✅ Dynamic Semester Headers -->
        <ng-container *ngFor="let cour of courseCodes">
          <th colspan="2">
            {{ cour.course_year_code }}
          </th>
        </ng-container>

        <th rowspan="2">Total Failed</th>
      </tr>

      <tr>
        <!-- ✅ Count & Subjects under each semester -->
        <ng-container *ngFor="let cour of courseCodes">
          <th>Count</th>
          <th>Subjects</th>
        </ng-container>
      </tr>
    </thead>

    <tbody>
      <tr *ngFor="let list of mainList; let i = index">
        <td>{{ i + 1 }}</td>
        <td>{{ list[0]?.hallticket_number }}</td>
        <td>{{ list[0]?.group_code }}</td>

        <!-- ✅ Dynamic Failed Data -->
        <ng-container *ngFor="let cour of courseCodes">
          <td>
            {{ findMarks(list, cour.course_year_code, 'semester_failed_count') }}
          </td>
          <td class="failed-text">
            {{ findMarks(list, cour.course_year_code, 'failed_subjects') }}
          </td>
        </ng-container>

        <td>{{ list[0]?.total_failed_count }}</td>
      </tr>
    </tbody>
  </table>
</div>

// src/app/(pages)/(protected)/admin-examination-management/admin-exam-reports/student-backlog-data/page.tsx
'use client'

import { Fragment, useEffect, useMemo, useState } from 'react'
import { FilteredPage } from '@/components/layout'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select } from '@/common/components/select'
import { GlobalFilterBarRow, GlobalFilterField } from '@/common/components/forms'
import {
  getAdmissionUnivFilters,
  getBatchWiseStudentBacklogReport,
  getFeeMasterCollegeFilters,
  listBatchesByCourse,
} from '@/services'
import {
  filterBatches,
  filterColleges,
  filterCourses,
  pickNum,
  pickText,
  type FilterRow,
} from '@/app/(pages)/(protected)/accounts-and-fees/fee-masters/_lib/fee-master-filters'
import { toastError, toastInfo } from '@/lib/toast'
import {
  Building2,
  FileSpreadsheet,
  GraduationCap,
  Layers,
  Printer,
  RotateCcw,
} from 'lucide-react'
import { printStudentBacklogReport } from '../_components/printStudentBacklogReport'

type AnyRow = Record<string, any>
type StudentSemesterRows = AnyRow[]

function exportHtmlTable(filename: string, title: string, bodyHtml: string) {
  const template = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>Worksheet</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>${title}${bodyHtml}</table></body></html>`
  const link = document.createElement('a')
  link.download = filename
  link.href = `data:application/vnd.ms-excel;base64,${window.btoa(unescape(encodeURIComponent(template)))}`
  link.click()
}

function toFilterRows(rows: AnyRow[]): FilterRow[] {
  return rows as FilterRow[]
}

/** Angular: group flat semester rows by hallticket_number. */
function groupByHallTicket(flatRows: AnyRow[]): StudentSemesterRows[] {
  const groups: Record<string, AnyRow[]> = {}
  for (const r of flatRows) {
    const key = String(r?.hallticket_number ?? r?.hall_ticketno ?? '').trim() || `row-${Math.random()}`
    if (!groups[key]) groups[key] = []
    groups[key].push(r)
  }
  return Object.values(groups)
}

function findMarks(list: AnyRow[], courseYearCode: string, field: string): string {
  const item = list.find((x) => String(x?.course_year_code ?? '') === courseYearCode)
  if (!item) return '-'
  const v = item[field]
  return v == null || String(v).trim() === '' ? '-' : String(v)
}

export default function StudentBacklogDataPage() {
  const employeeId = Number(globalThis?.localStorage?.getItem('employeeId') ?? 0)
  const orgId = Number(globalThis?.localStorage?.getItem('organizationId') ?? 0)

  const [loading, setLoading] = useState(false)
  const [filtersData, setFiltersData] = useState<FilterRow[]>([])
  const [batchesFilter, setBatchesFilter] = useState<FilterRow[]>([])
  const [domainBatches, setDomainBatches] = useState<FilterRow[]>([])

  const [collegeId, setCollegeId] = useState<number | null>(null)
  const [courseId, setCourseId] = useState<number | null>(null)
  const [batchId, setBatchId] = useState<number | null>(null)
  const [skipAutoSelect, setSkipAutoSelect] = useState(false)

  const [mainList, setMainList] = useState<StudentSemesterRows[]>([])
  const [courseYearCodes, setCourseYearCodes] = useState<string[]>([])
  const [searchText, setSearchText] = useState('')

  const colleges = useMemo(() => filterColleges(filtersData), [filtersData])
  const courses = useMemo(
    () => filterCourses(filtersData, collegeId),
    [filtersData, collegeId],
  )

  const batches = useMemo(() => {
    const fromProc = filterBatches(batchesFilter, courseId)
    if (fromProc.length > 0) return fromProc
    return filterBatches(domainBatches, courseId)
  }, [batchesFilter, domainBatches, courseId])

  const filteredList = useMemo(() => {
    const q = searchText.trim().toLowerCase()
    if (!q) return mainList
    return mainList.filter((list) => {
      const first = list[0] ?? {}
      const ht = pickText(first, ['hallticket_number', 'hall_ticketno']).toLowerCase()
      const group = pickText(first, ['group_code', 'groupCode']).toLowerCase()
      return ht.includes(q) || group.includes(q)
    })
  }, [mainList, searchText])

  useEffect(() => {
    let cancelled = false
    async function init() {
      setLoading(true)
      try {
        const collegeFilters = await getFeeMasterCollegeFilters(orgId, employeeId)
        if (cancelled) return

        let nextBatches = toFilterRows(collegeFilters.batchesData ?? [])
        if (nextBatches.length === 0) {
          const univFilters = await getAdmissionUnivFilters(orgId, employeeId).catch(() => null)
          nextBatches = toFilterRows(univFilters?.batchesData ?? [])
        }

        setFiltersData(toFilterRows(collegeFilters.filtersData ?? []))
        setBatchesFilter(nextBatches)

        const nextColleges = filterColleges(toFilterRows(collegeFilters.filtersData ?? []))
        setSkipAutoSelect(false)
        setCollegeId(nextColleges[0] ? pickNum(nextColleges[0], ['fk_college_id', 'collegeId']) : null)
      } catch {
        if (!cancelled) toastError('Failed to load filters')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    void init()
    return () => {
      cancelled = true
    }
  }, [orgId, employeeId])

  useEffect(() => {
    if (!collegeId) {
      setCourseId(null)
      return
    }
    if (skipAutoSelect) return
    const list = filterCourses(filtersData, collegeId)
    setCourseId(list[0] ? pickNum(list[0], ['fk_course_id', 'courseId']) : null)
  }, [collegeId, filtersData, skipAutoSelect])

  useEffect(() => {
    let cancelled = false
    async function loadDomainBatches() {
      if (!courseId) {
        setDomainBatches([])
        return
      }
      const fromProc = filterBatches(batchesFilter, courseId)
      if (fromProc.length > 0) {
        setDomainBatches([])
        return
      }
      try {
        const list = await listBatchesByCourse(courseId)
        if (cancelled) return
        setDomainBatches(
          toFilterRows(
            list.map((b) => ({
              fk_batch_id: b.batchId,
              batchId: b.batchId,
              batch_name: b.batchName,
              batchName: b.batchName,
              fk_course_id: courseId,
              courseId,
            })),
          ),
        )
      } catch {
        if (!cancelled) setDomainBatches([])
      }
    }
    void loadDomainBatches()
    return () => {
      cancelled = true
    }
  }, [courseId, batchesFilter])

  useEffect(() => {
    if (!courseId) {
      setBatchId(null)
      return
    }
    if (skipAutoSelect) return
    const list = batches
    setBatchId(list[0] ? pickNum(list[0], ['fk_batch_id', 'batchId']) : null)
  }, [courseId, batches, skipAutoSelect])

  async function handleGetReport() {
    if (!collegeId || !batchId) {
      toastError('Please select College and Batch')
      return
    }
    setLoading(true)
    setMainList([])
    setCourseYearCodes([])
    try {
      const flatRows = await getBatchWiseStudentBacklogReport({
        collegeId,
        courseId: courseId || 0,
        batchId,
      })
      if (flatRows.length === 0) {
        toastInfo('No data found for selected filters.')
        return
      }
      const uniqueYears = [
        ...new Set(
          flatRows
            .map((r) => String(r?.course_year_code ?? '').trim())
            .filter(Boolean),
        ),
      ]
      setCourseYearCodes(uniqueYears)
      setMainList(groupByHallTicket(flatRows))
    } catch (e) {
      toastError(e instanceof Error ? e.message : 'Failed to load report')
    } finally {
      setLoading(false)
    }
  }

  function handleReset() {
    setSkipAutoSelect(true)
    setCollegeId(null)
    setCourseId(null)
    setBatchId(null)
    setDomainBatches([])
    setMainList([])
    setCourseYearCodes([])
    setSearchText('')
  }

  function handleExportExcel() {
    if (filteredList.length === 0) return
    const topHeads = courseYearCodes.map((c) => `<th colspan="2">${c}</th>`).join('')
    const subHeads = courseYearCodes.map(() => `<th>Count</th><th>Subjects</th>`).join('')
    const head = `
      <tr>
        <th rowspan="2">Sno</th>
        <th rowspan="2">Hall ticket number</th>
        <th rowspan="2">Group code</th>
        ${topHeads}
        <th rowspan="2">Total Fail</th>
      </tr>
      <tr>${subHeads}</tr>`
    const body = filteredList
      .map((list, i) => {
        const first = list[0] ?? {}
        const sem = courseYearCodes
          .map(
            (code) =>
              `<td>${findMarks(list, code, 'semester_failed_count')}</td><td>${findMarks(list, code, 'failed_subjects')}</td>`,
          )
          .join('')
        return `<tr>
          <td>${i + 1}</td>
          <td>${pickText(first, ['hallticket_number', 'hall_ticketno'])}</td>
          <td>${pickText(first, ['group_code', 'groupCode'])}</td>
          ${sem}
          <td>${pickText(first, ['total_failed_count']) || '-'}</td>
        </tr>`
      })
      .join('')
    const title = `<tr><th colspan="${3 + courseYearCodes.length * 2 + 1}" style="text-align:center;font-size:18px;font-weight:bold;background:#f2f2f2;">Student Backlog Data</th></tr>`
    exportHtmlTable('Student Backlog Data.xls', title, `${head}${body}`)
  }

  function handlePrint() {
    if (filteredList.length === 0) return
    const college = colleges.find(
      (r) => pickNum(r, ['fk_college_id', 'collegeId']) === Number(collegeId),
    )
    printStudentBacklogReport(filteredList, {
      title: 'Student Backlog Data',
      collegeName: pickText(college ?? {}, ['college_name', 'collegeName']),
      courseYearCodes,
    })
  }

  return (
    <FilteredPage
      title="Student Backlog Data"
      filters={
        <GlobalFilterBarRow>
          <GlobalFilterField label="College" icon={Building2}>
            <Select
              value={collegeId ? String(collegeId) : null}
              onChange={(v) => {
                setSkipAutoSelect(false)
                setMainList([])
                setCourseYearCodes([])
                setCollegeId(v ? Number(v) : null)
              }}
              options={colleges.map((r) => ({
                value: String(pickNum(r, ['fk_college_id', 'collegeId'])),
                label: pickText(r, ['college_code', 'collegeCode', 'college_name']),
              }))}
              placeholder="College"
              searchable
              isLoading={loading && filtersData.length === 0}
            />
          </GlobalFilterField>
          <GlobalFilterField label="Course" icon={GraduationCap}>
            <Select
              value={courseId ? String(courseId) : null}
              onChange={(v) => {
                setSkipAutoSelect(false)
                setMainList([])
                setCourseYearCodes([])
                setCourseId(v ? Number(v) : null)
              }}
              options={courses.map((r) => ({
                value: String(pickNum(r, ['fk_course_id', 'courseId'])),
                label: pickText(r, ['course_code', 'courseCode', 'course_name']),
              }))}
              placeholder="Course"
              searchable
            />
          </GlobalFilterField>
          <GlobalFilterField label="Batch" icon={Layers}>
            <Select
              value={batchId ? String(batchId) : null}
              onChange={(v) => {
                setMainList([])
                setCourseYearCodes([])
                setBatchId(v ? Number(v) : null)
              }}
              options={batches.map((r) => ({
                value: String(pickNum(r, ['fk_batch_id', 'batchId'])),
                label: pickText(r, ['batch_name', 'batchName']),
              }))}
              placeholder="Batch"
              searchable
              isLoading={Boolean(courseId) && loading}
            />
          </GlobalFilterField>
          <div className="ml-auto flex shrink-0 flex-wrap items-center gap-3 self-end pb-0.5">
            <Button
              type="button"
              className="h-8 text-[12px]"
              onClick={() => void handleGetReport()}
              disabled={loading}
            >
              {loading ? 'Loading...' : 'Get Report'}
            </Button>
            <Button
              type="button"
              variant="outline"
              className="h-8 gap-1.5 text-[12px]"
              onClick={handleReset}
              title="Reset"
            >
              <RotateCcw className="h-3.5 w-3.5" />
              Reset
            </Button>
          </div>
        </GlobalFilterBarRow>
      }
      body={
        mainList.length > 0 ? (
          <div className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <p className="font-semibold text-foreground">Student Backlog Data</p>
              <div className="flex flex-wrap items-center gap-2">
                <Button
                  type="button"
                  variant="outline"
                  className="h-8 text-[12px]"
                  onClick={handleExportExcel}
                >
                  <FileSpreadsheet className="mr-1.5 h-3.5 w-3.5" />
                  Export Excel
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  className="h-8 text-[12px]"
                  onClick={handlePrint}
                >
                  <Printer className="mr-1.5 h-3.5 w-3.5" />
                  Print Report
                </Button>
                <Input
                  value={searchText}
                  onChange={(e) => setSearchText(e.target.value)}
                  placeholder="Search"
                  className="h-8 w-48 text-[12px]"
                />
              </div>
            </div>

            <div className="overflow-x-auto rounded-md border border-border">
              <table className="w-full min-w-[800px] text-left text-sm">
                <thead className="bg-muted/50">
                  <tr>
                    <th className="px-3 py-2 font-semibold" rowSpan={2}>
                      Sno
                    </th>
                    <th className="px-3 py-2 font-semibold" rowSpan={2}>
                      Hall ticket number
                    </th>
                    <th className="px-3 py-2 font-semibold" rowSpan={2}>
                      Group code
                    </th>
                    {courseYearCodes.map((code) => (
                      <th
                        key={`h-${code}`}
                        className="px-3 py-2 text-center font-semibold"
                        colSpan={2}
                      >
                        {code}
                      </th>
                    ))}
                    <th className="px-3 py-2 font-semibold" rowSpan={2}>
                      Total Fail
                    </th>
                  </tr>
                  <tr>
                    {courseYearCodes.map((code) => (
                      <Fragment key={`s-${code}`}>
                        <th className="px-3 py-2 font-semibold">Count</th>
                        <th className="px-3 py-2 font-semibold">Subjects</th>
                      </Fragment>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filteredList.map((list, i) => {
                    const first = list[0] ?? {}
                    return (
                      <tr
                        key={`${pickText(first, ['hallticket_number', 'hall_ticketno'])}-${i}`}
                        className="border-t"
                      >
                        <td className="px-3 py-1.5 text-center">{i + 1}</td>
                        <td className="px-3 py-1.5">
                          {pickText(first, ['hallticket_number', 'hall_ticketno'])}
                        </td>
                        <td className="px-3 py-1.5">
                          {pickText(first, ['group_code', 'groupCode'])}
                        </td>
                        {courseYearCodes.map((code) => (
                          <Fragment key={`${code}-${i}`}>
                            <td className="px-3 py-1.5 text-center">
                              {findMarks(list, code, 'semester_failed_count')}
                            </td>
                            <td className="px-3 py-1.5">
                              {findMarks(list, code, 'failed_subjects')}
                            </td>
                          </Fragment>
                        ))}
                        <td className="px-3 py-1.5 text-center">
                          {pickText(first, ['total_failed_count']) || '-'}
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        ) : null
      }
    />
  )
}
