// todo/Source/examination/exam-reports/exam-verification/exam-verification.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ParametersService } from 'app/main/services/parameters.service';

@Component({
  selector: 'app-exam-verification',
  templateUrl: './exam-verification.component.html',
  styleUrls: ['./exam-verification.component.scss']
})
export class ExamVerificationComponent implements OnInit {
  step = 0;  

  constructor(private router: Router,private parameterservice:ParametersService) { 
    this.parameterservice.back=''
  }

  ngOnInit(): void {
  }

  subjectWiseEvaluators(){
    this.router.navigate(['admin-examination-management/admin-exam-reports/subject-wise-evaluators-report'])
    this.parameterservice.back = 'back';

  }
  ExamAnswerSheet(){
    this.router.navigate(['admin-examination-management/admin-exam-reports/exam-answer-sheets-report'])
    this.parameterservice.back = 'back';


  }
  DailyEvaluatedReport(){
    this.router.navigate(['admin-examination-management/admin-exam-reports/daily-evaluated-report'])
    this.parameterservice.back = 'back';


  }
 
  ExamEvaluationReport(){
    this.router.navigate(['admin-examination-management/admin-exam-reports/exam-evaluation-report'])
    this.parameterservice.back = 'back';


  }
  // VerifyExamStatus(){
  //   this.router.navigate(['admin-examination-management/admin-exam-reports/exam-evaluation-report'])

  // }
  // VerifyExamMarks(){
    
  // }
  VerifyExamStatus(){
    this.router.navigate(['admin-examination-management/admin-post-examination/verify-exam-status'])
    this.parameterservice.back = 'back';

  
  }
  VerifyExamMarks(){
    this.router.navigate(['admin-examination-management/admin-post-examination/verify-exam-marks'])
    this.parameterservice.back = 'back';

    
  }
}


<div id="dashboard" class="page-layout simple">

    <div class="center" fusePerfectScrollbar>

        <!-- HEADER -->
        <div class="header pd-dash" fxLayout="column" fxLayoutAlign="space-between">

            <div fxLayout="column" class="link-header" fxLayoutAlign="center center" fxLayout.gt-xs="column"
            fxLayoutAlign.gt-xs="center start">
            <div class="black-fg" fxLayout="row" fxLayoutAlign="start center">
                <mat-icon class="secondary-text s-18 cursr" [routerLink]="'/dashboard'">home</mat-icon>
                <mat-icon class="secondary-text s-16">chevron_right</mat-icon>
                <span>Reports</span>
                <mat-icon class="secondary-text s-16">chevron_right</mat-icon>
                <span>Examination Reports</span>
                <mat-icon class="secondary-text s-16">chevron_right</mat-icon>
                <span> Exam Verification Report</span>
            </div>
        </div>
        </div>
      <div class="content">
        <mat-accordion style="width: 100%;padding: 22px 24px 0px 24px;">
            <mat-expansion-panel [expanded]="step === 0" hideToggle style="margin: 0px 25px;">
                <mat-expansion-panel-header>
                    <mat-panel-title>
                        <div fxLayout="column" fxLayoutAlign="center center" fxLayout.gt-xs="column" fxLayoutAlign.gt-xs="center start">
                            <div class="black-fg" fxLayout="row" fxLayoutAlign="start center">
                                <mat-icon class="fs  icon-align ">book</mat-icon>
                                <strong class="table-heads">Exam Verification Report</strong>
                            </div>
                        </div>
                    </mat-panel-title>
                    <!-- <label class="filter-align">Filter</label> -->
                    <!-- <mat-icon>filter_list</mat-icon> -->
                </mat-expansion-panel-header>
               
                    <div fxLayout="column" style="margin-top: 10px" class="mlr-15 inner-bkgrd">
                <div style="padding: 12px 0px 0px 0px;">
                  <div fxLayout="row">
                    <div  fxLayout="column" class="p-8 yar-bordr" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50">
                        <h2 class="ptag">1. Exam AnswerSheets Upload Report </h2>
                        <h3>this report gives count of no.of students register , Answerpaper upload for every subject. </h3>
                        <div class="divbuttons">
                            <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="ExamAnswerSheet()">Exam AnswerSheets Upload Report</button>
                        </div>
                    </div>
                    <div  fxLayout="column" class="p-8 yar-bordr" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50">
                        <h2 class="ptag">2. Subject Wise Evaluators List Report </h2>
                        <h3>This report will give all the evaluators list for every subject. </h3>
                        <div class="divbuttons">
                            <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="subjectWiseEvaluators()">Subject Wise Evaluators List Report</button>
                        </div>
                    </div>
                   
                </div>
                <!-- <div fxLayout="column" class="yar-bordr">
                    <div  fxLayout="column" class="p-8" fxFlex="100" fxFlex.gt-xs="100" fxFlex.gt-md="100">
                        <h2 class="ptag"> Subject Wise Evaluators Report </h2>
                        <h3>The objective of this is to update the status from Evaluated to Finalized.</h3>
                    </div>
                      <div class="divbuttons">
                        <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="subjectWiseEvaluators()">Subject Wise Evaluators Report</button>
                      </div>
                </div> -->
                <div fxLayout="row">
                    <div  fxLayout="column" class="p-8 yar-bordr" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50">
                        <h2 class="ptag">3. Exam Evaluation Status Report </h2>
                        <h3>This report list of all evaluation status by evaluators for on exam. </h3>
                        <div  class="divbuttons">
                            <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="ExamEvaluationReport()">Exam Evaluation Status Report</button>
                        </div>
                    </div>
                    <div  fxLayout="column" class="p-8 yar-bordr" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50">
                        <h2 class="ptag">4. Evaluator report in data range</h2>
                        <h3> This report will give no.of evaluations done by evaluators in a date range. </h3>
                        <div  class="divbuttons">
                            <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="DailyEvaluatedReport()">Daily Evaluated Report</button>
                        </div>
                    </div>
                    
                   
                </div>
                <div fxLayout="row">
                    <!-- <div  fxLayout="column" class="p-8 yar-bordr" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50">
                        <h2 class="ptag">5. Verify Exam Status</h2>
                        <h3>The objective of this update is to review student assignments, OMR details, and answer papers. </h3>
                        <div  class="divbuttons">
                            <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="VerifyExamStatus()">Verify Exam Status</button>
                        </div>
                    </div> -->
                    <div  fxLayout="column" class="p-8 yar-bordr" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50">
                        <h2 class="ptag">5. Marks Entered Status </h2>
                        <h3>This report  will give list of evaluator marks status.</h3>
                        <div  class="divbuttons">
                            <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="VerifyExamMarks()">Verify Exam Marks</button>
                        </div>
                    </div>
                    <div  fxLayout="column" class="p-8" fxFlex="100" fxFlex.gt-xs="50" fxFlex.gt-md="50"></div>
                </div>
                <!-- <div fxLayout="column" class="yar-bordr">
                    <div  fxLayout="column" class="p-8" fxFlex="100" fxFlex.gt-xs="100" fxFlex.gt-md="100">
                        <h2 class="ptag">Verify Exam Marks</h2>
                        <h3> Marks will be Finalized after Finalized Evaluation Status</h3>
                    </div>
                    <div class="divbuttons">
                        <button mat-raised-button class="action-btn addBtn" color="accent"  (click)="VerifyExamMarks()">Verify Exam Marks</button>
                      </div>
                    
                </div> -->
                </div>    
            </div> 
            </mat-expansion-panel>
        </mat-accordion>
      
    </div>
        </div>
        </div>

// src/app/(pages)/(protected)/admin-examination-management/exam-reports/exam-verification/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { FilteredPage } from "@/components/layout";
import { Button } from "@/components/ui/button";

const REPORTS = [
  {
    title: "1. Exam AnswerSheets Upload Report",
    description:
      "this report gives count of no.of students register , Answerpaper upload for every subject.",
    button: "Exam AnswerSheets Upload Report",
    // Angular: admin-exam-reports/exam-answer-sheets-report
    href: "/admin-examination-management/exam-reports/exam-answer-sheets-report",
  },
  {
    title: "2. Subject Wise Evaluators List Report",
    description:
      "This report will give all the evaluators list for every subject.",
    button: "Subject Wise Evaluators List Report",
    // Angular: admin-exam-reports/subject-wise-evaluators-report
    href: "/admin-examination-management/exam-reports/subject-wise-evaluators-report",
  },
  {
    title: "3. Exam Evaluation Status Report",
    description:
      "This report list of all evaluation status by evaluators for on exam.",
    button: "Exam Evaluation Status Report",
    // Angular ExamEvaluationReport → exam-evaluation-report
    href: "/admin-examination-management/exam-reports/exam-evaluation-report",
  },
  {
    title: "4. Evaluator report in data range",
    description:
      "This report will give no.of evaluations done by evaluators in a date range.",
    button: "Daily Evaluated Report",
    // Angular DailyEvaluatedReport → daily-evaluated-report
    href: "/admin-examination-management/exam-reports/daily-evaluated-report",
  },
  {
    title: "5. Marks Entered Status",
    description: "This report  will give list of evaluator marks status.",
    button: "Verify Exam Marks",
    // Angular VerifyExamMarks → admin-post-examination/verify-exam-marks
    href: "/admin-examination-management/post-examination/verify-exam-marks",
  },
] as const;

function ReportCard({
  title,
  description,
  button,
  onClick,
}: Readonly<{
  title: string;
  description: string;
  button: string;
  onClick: () => void;
}>) {
  return (
    <div className="flex flex-col rounded-sm border-2 border-[#89c5ff] p-3 mx-1 mb-4 min-h-[140px]">
      <h2 className="text-[15px] font-semibold text-foreground">{title}</h2>
      <p className="mt-1 text-[13px] text-muted-foreground flex-1">{description}</p>
      <div className="mt-3 flex justify-end">
        <Button
          type="button"
          className="h-10 min-w-[40%] px-3 text-[13px]"
          onClick={onClick}
        >
          {button}
        </Button>
      </div>
    </div>
  );
}

export default function ExamVerificationReportPage() {
  const router = useRouter();

  return (
    <FilteredPage
      title="Exam Verification Report"
      filtersCollapsible={false}
      filters={
        <div className="grid grid-cols-1 gap-1 md:grid-cols-2 pt-1">
          {REPORTS.map((item) => (
            <ReportCard
              key={item.href}
              title={item.title}
              description={item.description}
              button={item.button}
              onClick={() => {
                // Angular ParametersService.back = 'back' for return navigation
                try {
                  sessionStorage.setItem("examVerificationBack", "back");
                } catch {
                  /* ignore */
                }
                router.push(item.href);
              }}
            />
          ))}
        </div>
      }
    />
  );
}
